const generate = require('./generate');

const PaymentGatewayFunctions = [
    'payment-service-api-prod-accesstoken',
    'payment-service-api-prod-app',
    'payment-service-api-prod-confirm',
    'payment-service-api-prod-eventStream',
    'payment-service-api-prod-gatewayStatus',
    'payment-service-api-prod-gcashCallback',
    'payment-service-api-prod-adyenCallback',
    'payment-service-api-prod-gcashPaymentQuery',
    'payment-service-api-prod-ipay88Callback',
    'payment-service-api-prod-ipay88PaymentQuery',
    'payment-service-api-prod-lukeCron',
    'payment-service-api-prod-overallTransactions',
    'payment-service-api-prod-refreshtoken',
    'payment-service-api-prod-register',
    //'payment-service-api-prod-deleteUser',
    'payment-service-api-prod-resendCode',
    'payment-service-api-prod-transactions',
];

const GlobeAtHomeFileServiceFunctions = [
    'bbapp-file-service-v2-prod-bill-statement',
    'bbapp-file-service-v2-prod-authorizer',
    'bbapp-file-service-v2-prod-access-token',
];

const GlobeAtHomeAPIFunctions = [
    'bb-api-new-v2-prod-access-token',
    'bb-api-new-v2-prod-accounts',
    'bb-api-new-v2-prod-analytics',
    'bb-api-new-v2-prod-authorizer',
    'bb-api-new-v2-prod-cms',
    'bb-api-new-v2-prod-content-management',
    'bb-api-new-v2-prod-device',
    'bb-api-new-v2-prod-email-complaint',
    'bb-api-new-v2-prod-external',
    'bb-api-new-v2-prod-games',
    'bb-api-new-v2-prod-globelabs',
    'bb-api-new-v2-prod-login',
    'bb-api-new-v2-prod-notification',
    'bb-api-new-v2-prod-payment-methods',
    'bb-api-new-v2-prod-promotion',
    'bb-api-new-v2-prod-register',
    'bb-api-new-v2-prod-shop',
    'bb-api-new-v2-prod-takeovers',
    'bb-api-new-v2-prod-transfer-location',
    'bb-api-new-v2-prod-vouchers',
    'bb-api-new-v2-prod-work-order',
];

const GlobeOne = [
    'globeone-es-ftw002-stg-SendSmsNotification',
    'globeone-es-ftw002-stg-SendEmailNotification',
    'globeone-es-ftw002-stg-PisGetPosUrlBody',
    'globeone-es-ftw002-stg-PisGetPosUrl',
    'globeone-es-ftw002-stg-PisGetOrListByAccNoAndYear',
    'globeone-es-ftw002-stg-EsbRetrieveSubscriberUsage',
    'globeone-es-ftw002-stg-EsbRetrieveData',
    'globeone-es-ftw002-stg-EsbRetrieveBillingStatement',
    'globeone-es-ftw002-stg-EsbRetrieveBillMediaByBAId',
    'globeone-es-ftw002-stg-EsbProvisionPromo',
    'globeone-es-ftw002-stg-EsbProvisionGenericPromo',
    'globeone-es-ftw002-stg-EsbProvDeprovPromo',
    'globeone-es-ftw002-stg-EsbGetUnBillChargesByMsisdn',
    'globeone-es-ftw002-stg-EsbGetSubscriberByMsisdn',
    'globeone-es-ftw002-stg-EsbGetSimDetails',
    'globeone-es-ftw002-stg-EsbGetOutStandingBalance',
    'globeone-es-ftw002-stg-EsbGetLoyaltySubscriberAvailableRewards',
    'globeone-es-ftw002-stg-EsbGetLoyaltyProgramId',
    'globeone-es-ftw002-stg-EsbGetListTransactionHistory',
    'globeone-es-ftw002-stg-EsbGetDetailsByMsisdn',
    'globeone-es-ftw002-stg-EsbGetCustomerDetailsByMsisdn',
    'globeone-es-ftw002-stg-EsbGetCaseDetailsByContactID',
    'globeone-es-ftw002-stg-EsbGetBillListByMsisdn',
    'globeone-es-ftw002-stg-EsbGetActiveProducts',
    'globeone-es-ftw002-stg-EsbDeprovisionPromo',
    'globeone-es-ftw002-stg-EsbDeprovisionGenericPromo',
    'globeone-es-ftw002-stg-AccountRecycleStatus',
    'globeone-es-ftw003-stg-EsbChangePlan',
    'globeone-es-ftw003-stg-EsbGenericCreateCase',
    'globeone-es-ftw003-stg-EsbChangeCreditLimit',
    'globeone-es-ftw003-stg-EsbChangeProductStatus',
    'globeone-es-ftw003-stg-EsbCloseCase',
    'globeone-es-ftw003-stg-EsbUpdateBillMediaByBaId',
    'globeone-es-ftw003-stg-OcspWirelessListAccounts',
    'globeone-es-ftw003-stg-OcspWirelessAddAccount',
    'globeone-es-ftw003-stg-OcspWirelessDeleteAccount',
    'globeone-es-ftw003-stg-OcspVerifyAccount',
    'globeone-es-ftw003-stg-OcspPromoSubscriptionUsage',
    'globeone-es-ftw003-stg-OcspActivePromoSubscription',
    'globeone-es-ftw008-stg-EsbRetrieveRechargeInstruction',
    'globeone-es-ftw008-stg-EsbChangeLoadingSchedule',
    'globeone-es-ftw008-stg-EsbRetrieveSubscriberDetailsByMsisdn',
    'globeone-es-ftw008-stg-EsbBalanceInquiry',
    'globeone-es-ftw008-stg-GetTopUpHistory',
    'globeone-es-ftw008-stg-EsbProvisionService',
    'globeone-es-ftw008-stg-EsbDeprovisionService',
    'globeone-es-ftw008-stg-EsbWrapDeprovisionService',
    'globeone-es-ftw008-stg-EsbWrapProvisionService',
    'globeone-es-ftw008-stg-OcspPromoSubscriptionUsage',
    'globeone-es-ftw008-stg-OcspActivePromoSubscription',
    'globeone-es-ftw008-stg-EsbListSubscribedServices',
    'globeone-es-ftw008-stg-EsbGetSubscriberProduct',
    'globeone-es-ftw011-stg-AccountValidation',
    'globeone-es-ftw011-stg-BbAppGetAccountDetail',
    'globeone-es-ftw011-stg-BbAppGetVerifiedStatus',
    'globeone-es-ftw011-stg-DumpCRDFileToRepap',
    'globeone-es-ftw011-stg-EsbGetAccountInfo',
    'globeone-es-ftw011-stg-EsbGetAssignedProducts',
    'globeone-es-ftw011-stg-EsbGetBillingHistoryDump',
    'globeone-es-ftw011-stg-EsbGetBillingInfo',
    'globeone-es-ftw011-stg-EsbGetCustomerInfo',
    'globeone-es-ftw011-stg-EsbGetICCBSDetail',
    'globeone-es-ftw011-stg-EsbGetPaymentHistoryDump',
    'globeone-es-ftw011-stg-EsbGetResourceInfo',
    'globeone-es-ftw011-stg-EsbGetSubscriberState',
    'globeone-es-ftw011-stg-EsbGetWirelineBoosterDump',
    'globeone-es-ftw011-stg-EsbProvisionPromoById',
    'globeone-es-ftw011-stg-EsbRequestPaymentToken',
    'globeone-es-ftw011-stg-EsbRetrieveAccountBarringInfo',
    'globeone-es-ftw011-stg-EsbVerifyEmailAddressAndMobileNumber',
    'globeone-es-ftw011-stg-SnsSendSMS',
    'globeone-es-ftw011-stg-SubscribePromo',
    'globeone-es-ftw011-stg-VerificationHPW',
    'globeone-es-ftw011-prod-TransportGetBillList',
    'globeone-es-ftw011-prod-TransportViewBill',
];

module.exports = async () => {
    await generate('PaymentGateway', 'Payment Gateway', 'arn:aws:lambda:ap-southeast-1:073504361408:function:', 'Tier 2A', PaymentGatewayFunctions);
    await generate('GlobeAtHomeFileService', 'Globe at Home', 'arn:aws:lambda:ap-southeast-1:073504361408:function:', 'Tier 2A', GlobeAtHomeFileServiceFunctions);
    await generate('GlobeAtHomeAPI', 'Globe at Home', 'arn:aws:lambda:ap-southeast-1:073504361408:function:', 'Tier 2A', GlobeAtHomeAPIFunctions);
    await generate('GlobeOne', 'Globe One', 'arn:aws:lambda:ap-southeast-1:073504361408:function:', 'Tier 2A', GlobeOne);
}